#+title:  Lab Integration Kit
#+SETUPFILE: ./org-templates/level-0.org

* Introduction

  Welcome to the Virtual Labs Version 1.0.0 Lab Integration Kit. This kit contains both software and user documenation 
  to help integrators:

- deploy a lab automatically and
- structure their labs to comply with a standard UI template
  
* Structure of this kit

#+BEGIN_example
-  user-docs
      |
      ---- index.html (instructions on the usage of the kit)
-  ovpl-kit
      |
      ----- user-docs 
               |
               ----  index.html (information about the usage)
      |
      ----- scripts (set up CentOS as a hosting environment)
      |
      ----- ovpl (soruce code of auto deployment)
      |
-  ui-kit
      |
      ----- user-docs 
               |
               ----  index.html (steps to convert a lab to UI 1.0 format)
      |
      ----- scripts (needed for conversion to UI 1.0 format)
      |
      ----- src ( contains the UI 1.0 template )

#+END_example

* Pre-requisites for using this kit

  - To use the lab integration kit, you should know how to ::

   - execute basic shell commands in CentOS 6.5
   - create and delete a container in OpenVZ virtual environment
   - create or modify an HTML page and write a code in JavaScript
   - use git, a version control tool
   - create repositories on github.com

  - Reference Material ::

    - Frequently asked questions on basic shell commands ([[./faq.org]])
    - Concepts of Virtualization ([[./intro-to-openvz.org]])
    - HTML and Javascript ([[http://www.w3schools.com/html/]] , [[http://www.w3schools.com/js/]])
    - Version Control and GitHub ([[./version-control.org]])

* Documentation

  Documentation for OVPL Kit/ADS (Auto Deployment Service), UI KIT and Integration Levels is
  here:
  
  Note: In this document OVPL and ADS terms are used interchangeably. 
  Currently, OVPL is renamed to ADS (Auto Deployment Service). It still uses the same OVPL repository in lab deployment process.
  

[[https://github.com/vlead/setup-ovpl-centos/blob/master/user-docs/how-to-deploy-a-lab.org][Documentation for OVPL KIT]] 

[[https://github.com/vlead/ui-1.0-toolkit/blob/master/user-docs/index.org][Documentation for UI KIT]]

[[https://github.com/Virtual-Labs/lik/blob/master/user-docs/definition-of-integration-levels.org][Documentation for Integration Levels]]

